tests: Avoid backgrounds for registry tests
Cucumber 2.4.0 crashes on tests with backgrounds
and Around hooks that run block multiple times.

Error is:

undefined method `describe_to' for nil:NilClass (NoMethodError)
/home/test/.gem/ruby/gems/cucumber-2.4.0/lib/cucumber/formatter/legacy_api/adapter.rb:939:in `initialize'
/home/test/.gem/ruby/gems/cucumber-2.4.0/lib/cucumber/formatter/legacy_api/adapter.rb:546:in `new'
/home/test/.gem/ruby/gems/cucumber-2.4.0/lib/cucumber/formatter/legacy_api/adapter.rb:546:in `after'
/home/test/.gem/ruby/gems/cucumber-2.4.0/lib/cucumber/formatter/legacy_api/adapter.rb:396:in `switch_to_child'
/home/test/.gem/ruby/gems/cucumber-2.4.0/lib/cucumber/formatter/legacy_api/adapter.rb:324:in `switch_step_container'
/home/test/.gem/ruby/gems/cucumber-2.4.0/lib/cucumber/formatter/legacy_api/adapter.rb:357:in `print_step'
/home/test/.gem/ruby/gems/cucumber-2.4.0/lib/cucumber/formatter/legacy_api/adapter.rb:239:in `after_test_step'
/home/test/.gem/ruby/gems/cucumber-2.4.0/lib/cucumber/formatter/legacy_api/adapter.rb:95:in `after_test_step'
/home/test/.gem/ruby/gems/cucumber-2.4.0/lib/cucumber/formatter/legacy_api/adapter.rb:37:in `after_test_step'
/home/test/.gem/ruby/gems/cucumber-2.4.0/lib/cucumber/formatter/fanout.rb:16:in `block in method_missing'
/home/test/.gem/ruby/gems/cucumber-2.4.0/lib/cucumber/formatter/fanout.rb:15:in `each'
/home/test/.gem/ruby/gems/cucumber-2.4.0/lib/cucumber/formatter/fanout.rb:15:in `method_missing'
/home/test/.gem/ruby/gems/cucumber-core-1.5.0/lib/cucumber/core/test/runner.rb:34:in `around_hook'
/home/test/.gem/ruby/gems/cucumber-core-1.5.0/lib/cucumber/core/test/around_hook.rb:11:in `describe_to'
/home/test/.gem/ruby/gems/cucumber-core-1.5.0/lib/cucumber/core/test/case.rb:106:in `block (2 levels) in compose_around_hooks'
/home/test/.gem/ruby/gems/cucumber-core-1.5.0/lib/cucumber/core/test/case.rb:107:in `call'
/home/test/.gem/ruby/gems/cucumber-core-1.5.0/lib/cucumber/core/test/case.rb:107:in `compose_around_hooks'
/home/test/.gem/ruby/gems/cucumber-core-1.5.0/lib/cucumber/core/test/case.rb:24:in `block in describe_to'
/home/test/.gem/ruby/gems/cucumber-core-1.5.0/lib/cucumber/core/test/runner.rb:18:in `call'
/home/test/.gem/ruby/gems/cucumber-core-1.5.0/lib/cucumber/core/test/runner.rb:18:in `test_case'
/home/test/.gem/ruby/gems/cucumber-core-1.5.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
/home/test/.gem/ruby/gems/cucumber-2.4.0/lib/cucumber/filters/prepare_world.rb:11:in `test_case'
/home/test/.gem/ruby/gems/cucumber-core-1.5.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
/home/test/.gem/ruby/gems/cucumber-2.4.0/lib/cucumber/filters/apply_around_hooks.rb:8:in `test_case'
/home/test/.gem/ruby/gems/cucumber-core-1.5.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
/home/test/.gem/ruby/gems/cucumber-2.4.0/lib/cucumber/filters/apply_after_hooks.rb:5:in `test_case'
/home/test/.gem/ruby/gems/cucumber-core-1.5.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
/home/test/.gem/ruby/gems/cucumber-2.4.0/lib/cucumber/filters/apply_before_hooks.rb:5:in `test_case'
/home/test/.gem/ruby/gems/cucumber-core-1.5.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
/home/test/.gem/ruby/gems/cucumber-2.4.0/lib/cucumber/filters/apply_after_step_hooks.rb:8:in `test_case'
/home/test/.gem/ruby/gems/cucumber-core-1.5.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
/home/test/.gem/ruby/gems/cucumber-2.4.0/lib/cucumber/filters/activate_steps.rb:11:in `test_case'
/home/test/.gem/ruby/gems/cucumber-core-1.5.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
/home/test/.gem/ruby/gems/cucumber-2.4.0/lib/cucumber/filters/quit.rb:11:in `test_case'
/home/test/.gem/ruby/gems/cucumber-core-1.5.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
/home/test/.gem/ruby/gems/cucumber-core-1.5.0/lib/cucumber/core/test/filters/locations_filter.rb:17:in `block in done'
/home/test/.gem/ruby/gems/cucumber-core-1.5.0/lib/cucumber/core/test/filters/locations_filter.rb:16:in `each'
/home/test/.gem/ruby/gems/cucumber-core-1.5.0/lib/cucumber/core/test/filters/locations_filter.rb:16:in `done'
/home/test/.gem/ruby/gems/cucumber-core-1.5.0/lib/cucumber/core/filter.rb:61:in `done'
/home/test/.gem/ruby/gems/cucumber-core-1.5.0/lib/cucumber/core/test/filters/tag_filter.rb:18:in `done'
/home/test/.gem/ruby/gems/cucumber-core-1.5.0/lib/cucumber/core/compiler.rb:23:in `done'
/home/test/.gem/ruby/gems/cucumber-core-1.5.0/lib/cucumber/core/gherkin/parser.rb:35:in `done'
/home/test/.gem/ruby/gems/cucumber-core-1.5.0/lib/cucumber/core.rb:29:in `parse'
/home/test/.gem/ruby/gems/cucumber-core-1.5.0/lib/cucumber/core.rb:18:in `compile'
/home/test/.gem/ruby/gems/cucumber-2.4.0/lib/cucumber/runtime.rb:67:in `run!'
/home/test/.gem/ruby/gems/cucumber-2.4.0/lib/cucumber/cli/main.rb:32:in `execute!'
/home/test/.gem/ruby/gems/cucumber-2.4.0/bin/cucumber:8:in `<top (required)>'
/home/test/bin/cucumber:23:in `load'
/home/test/bin/cucumber:23:in `<main>'

Signed-off-by: Dmitry Fleytman <dmitry@daynix.com>